#!/bin/bash
/usr/bin/chromium --no-sandbox --no-xshm --disable-dev-shm-usage --disable-gpu --disable-features=VizDisplayCompositor --no-default-browser-check --no-first-run --disable-popup-blocking --disable-new-avatar-menu "$@"
